// projects/rawkode.academy/website/src/components/video/player.tsx
import { useEffect, useRef } from "react";
import Hls from "hls.js";
import { actions } from "astro:actions";

interface VideoPlayerProps {
  videoId: string;
  width?: number;
  height?: number;
  autoPlay?: boolean;
  thumbnailUrl: string;
  onError?: (error: Error) => void;
  onReady?: () => void;
}

export type VideoAnalyticsEvent =
  | VideoStartedEvent
  | VideoPausedEvent
  | VideoSeekedEvent
  | VideoCompletedEvent
  | VideoProgressedEvent;

interface VideoStartedEvent {
  action: "video_started";
  videoId: string;
  seconds: number;
}

interface VideoPausedEvent {
  action: "video_paused";
  videoId: string;
  seconds: number;
}

interface VideoSeekedEvent {
  action: "video_seeked";
  videoId: string;
  seconds: number;
}

interface VideoCompletedEvent {
  action: "video_completed";
  videoId: string;
}

interface VideoProgressedEvent {
  action: "video_progressed";
  videoId: string;
  percent: number;
}

async function trackVideoEvent(event: VideoAnalyticsEvent) {
  try {
    await actions.trackVideoEvent(event);
  } catch (error) {
    if (error instanceof Error) {
      console.error("Failed to track video event:", error.message);
    } else {
      console.error("Failed to track video event:", error);
    }
  }
}

export default function VideoPlayer({
  videoId,
  thumbnailUrl,
  autoPlay = false,
  onError,
  onReady,
}: VideoPlayerProps) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const hlsRef = useRef<Hls | null>(null);
  const progressMilestonesRef = useRef<Set<number>>(new Set());
  const src = `https://videos.rawkode.academy/${videoId}/stream.m3u8`;

  useEffect(() => {
    if (!videoRef.current) return;

    if (Hls.isSupported()) {
      hlsRef.current = new Hls({
        enableWorker: true,
        lowLatencyMode: true,
      });

      hlsRef.current.loadSource(src);
      hlsRef.current.attachMedia(videoRef.current);

      hlsRef.current.on(Hls.Events.MANIFEST_PARSED, () => {
        onReady?.();
        if (autoPlay) {
          videoRef.current?.play();
        }
      });

      hlsRef.current.on(Hls.Events.ERROR, (_, data) => {
        if (data.fatal) {
          onError?.(new Error(data.details));
        }
      });
    } else if (videoRef.current.canPlayType("application/vnd.apple.mpegurl")) {
      // Native HLS support (Safari)
      videoRef.current.src = src;
      videoRef.current.addEventListener("loadedmetadata", () => {
        onReady?.();
      });
    } else {
      onError?.(new Error("HLS not supported"));
    }

    return () => {
      if (hlsRef.current) {
        hlsRef.current.destroy();
      }
    };
  }, [src, autoPlay]);

  return (
    <video
      ref={videoRef}
      width="100%"
      controls
      playsInline
      poster={thumbnailUrl}
      onPlay={() => {
        const event: VideoStartedEvent = {
          action: "video_started",
          videoId,
          seconds: videoRef.current?.currentTime || 0,
        };
        trackVideoEvent(event);
      }}
      onPause={() => {
        const event: VideoPausedEvent = {
          action: "video_paused",
          videoId,
          seconds: videoRef.current?.currentTime || 0,
        };
        trackVideoEvent(event);
      }}
      onSeeked={() => {
        const event: VideoSeekedEvent = {
          action: "video_seeked",
          videoId,
          seconds: videoRef.current?.currentTime || 0,
        };
        trackVideoEvent(event);
      }}
      onTimeUpdate={() => {
        if (!videoRef.current) return;
        const progress = Math.floor(
          (videoRef.current.currentTime / videoRef.current.duration) * 100,
        );

        // Check for specific milestones (5%, 10%, 25%, 50%, 75%, 95%)
        const milestones = [5, 10, 25, 50, 75, 95];
        for (const milestone of milestones) {
          if (
            progress >= milestone &&
            !progressMilestonesRef.current.has(milestone)
          ) {
            progressMilestonesRef.current.add(milestone);
            const event: VideoProgressedEvent = {
              action: "video_progressed",
              videoId,
              percent: milestone,
            };
            trackVideoEvent(event);
          }
        }
      }}
      onEnded={() => {
        const event: VideoCompletedEvent = {
          action: "video_completed",
          videoId,
        };
        trackVideoEvent(event);
      }}
    />
  );
}

// projects/rawkode.academy/website/src/components/video/player.vue
<script lang="ts" setup>
import 'vidstack/bundle';
import { onMounted, ref } from 'vue';
import { actions } from 'astro:actions';

const props = defineProps<{
  videoId: string;
  thumbnailUrl: string;
  autoPlay?: boolean;
}>();

const player = ref<HTMLElement | null>(null);
const progressMilestones = ref<Set<number>>(new Set());

type VideoAnalyticsEvent =
  | { action: 'video_started'; videoId: string; seconds: number }
  | { action: 'video_paused'; videoId: string; seconds: number }
  | { action: 'video_seeked'; videoId: string; seconds: number }
  | { action: 'video_completed'; videoId: string }
  | { action: 'video_progressed'; videoId: string; percent: number };

async function trackVideoEvent(event: VideoAnalyticsEvent) {
  try {
    await actions.trackVideoEvent(event);
  } catch (error) {
    if (error instanceof Error) {
      console.error('Failed to track video event:', error.message);
    } else {
      console.error('Failed to track video event:', error);
    }
  }
}

onMounted(() => {
  if (!player.value) return;

  // Handle media events
  player.value.addEventListener('play', () => {
    const mediaEl = player.value?.querySelector('video');
    if (!mediaEl) return;

    const event: VideoAnalyticsEvent = {
      action: 'video_started',
      videoId: props.videoId,
      seconds: mediaEl.currentTime || 0,
    };
    trackVideoEvent(event);
  });

  player.value.addEventListener('pause', () => {
    const mediaEl = player.value?.querySelector('video');
    if (!mediaEl) return;

    const event: VideoAnalyticsEvent = {
      action: 'video_paused',
      videoId: props.videoId,
      seconds: mediaEl.currentTime || 0,
    };
    trackVideoEvent(event);
  });

  player.value.addEventListener('seeked', () => {
    const mediaEl = player.value?.querySelector('video');
    if (!mediaEl) return;

    const event: VideoAnalyticsEvent = {
      action: 'video_seeked',
      videoId: props.videoId,
      seconds: mediaEl.currentTime || 0,
    };
    trackVideoEvent(event);
  });

  player.value.addEventListener('ended', () => {
    const event: VideoAnalyticsEvent = {
      action: 'video_completed',
      videoId: props.videoId,
    };
    trackVideoEvent(event);
  });

  player.value.addEventListener('timeupdate', () => {
    const mediaEl = player.value?.querySelector('video');
    if (!mediaEl || !mediaEl.duration) return;

    const progress = Math.floor((mediaEl.currentTime / mediaEl.duration) * 100);

    // Check for specific milestones (5%, 10%, 25%, 50%, 75%, 95%)
    const milestones = [5, 10, 25, 50, 75, 95];
    for (const milestone of milestones) {
      if (progress >= milestone && !progressMilestones.value.has(milestone)) {
        progressMilestones.value.add(milestone);
        const event: VideoAnalyticsEvent = {
          action: 'video_progressed',
          videoId: props.videoId,
          percent: milestone,
        };
        trackVideoEvent(event);
      }
    }
  });
});
</script>

<template>
  <div class="w-full aspect-video">
    <media-player
      ref="player"
      :autoplay="!!autoPlay"
      class="w-full h-full"
    >
      <media-provider>
        <source :src="`https://videos.rawkode.academy/${videoId}/stream.m3u8`" type="application/x-mpegurl" />
        <media-poster
          class="vds-poster"
          :src="thumbnailUrl"
          :alt="`Thumbnail for ${videoId}`"
        ></media-poster>
      </media-provider>
      <media-video-layout></media-video-layout>
    </media-player>
  </div>
</template>
