// projects/rawkode.academy/web/src/components/hero/typewriter.vue
<script setup lang="ts">
import VueWriter from 'vue-writer';

export interface Props {
	rotatedPrefixes: string[],
	suffix: string,
	highlight: string,
	image: ImageMetadata,
}
const props = defineProps<Props>();
</script>

<style>
.is-typed span.typed {
	@apply bg-gradient-to-br from-primary to-secondary bg-clip-text text-transparent;
}

.is-typed span.cursor {
	display: inline-block;
	width: 3px;
	animation: blink 1s infinite;

	@apply bg-gradient-to-br from-primary to-secondary bg-clip-text text-transparent;
}

.is-typed span.underscore {
	display: inline-flex;
	width: 10px;
	height: 1px;
	align-items: flex-end;
	background-color: black;
	animation: blink 1s infinite;
}

.is-typed span.cursor.typing {
	animation: none;
}

@keyframes blink {
	49% {
		background-color: green;
	}

	50% {
		background-color: transparent;
	}

	99% {
		background-color: transparent;
	}
}
</style>

<template>
	<section class="bg-white dark:bg-black">
		<div class="grid px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
			<div class="mr-auto place-self-center lg:col-span-7">
				<h1
					class="mb-4 text-4xl font-semibold tracking-tight leading-none md:text-5xl xl:text-6xl text-black dark:text-white">
					<VueWriter :type-speed="100" :erase-speed="50" :array="props.rotatedPrefixes"></VueWriter> {{ props.suffix }}
				</h1>
				<p class="mb-6 font-light text-gray-600 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">
					Navigating the Cloud Native landscape can be tough. It's rapidly evolving and just keeping your head above water
					can be tough. We're here to help.
				</p>
				<a href="#"
					class="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg text-black bg-gradient-to-br from-primary to-secondary hover:from-secondary hover:to-primary">
					Free Membership
					<svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
						<path fill-rule="evenodd"
							d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
							clip-rule="evenodd"></path>
					</svg>
				</a>

				<a href="#"
					class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
					Learn more
				</a>
			</div>
			<div class="hidden lg:mt-0 lg:col-span-5 lg:flex">
				<img :src="props.image.src" alt="Mix of Cloud Nativ

e Project Logos">
			</div>
		</div>
	</section>
</template>

// projects/rawkode.academy/platform/web/src/components/hero/typewriter.tsx
import { TypeAnimation } from "react-type-animation";

interface ButtonProps {
  text: string;
  link: string;
  newWindow?: boolean;
}

interface Props {
  rotatedPrefixes: string[];
  suffix: string;
  highlight: string;
  image: ImageMetadata;
  primaryButton: ButtonProps;
  secondaryButton: ButtonProps;
}

const shuffle = (array: string[]): string[] => {
  return array.sort(() => Math.random() - 0.5);
};

const Typewriter = (props: Props) => {
  return (
    <section className="bg-white dark:bg-black">
      <div className="grid px-2 py-8 mx-auto lg:gap-4 xl:gap-0 lg:py-16 lg:grid-cols-12">
        <div className="mr-auto place-self-center lg:col-span-8">
          <h1 className="mb-4 text-4xl font-semibold tracking-tight leading-none md:text-5xl xl:text-6xl text-black dark:text-white">
            <TypeAnimation
              className="bg-gradient-to-br from-primary to-secondary bg-clip-text text-transparent"
              sequence={shuffle(props.rotatedPrefixes).reduce<
                Array<string | number>
              >((acc, prefix: string) => [...acc, prefix, 1250], [])}
              wrapper="span"
              preRenderFirstString={true}
              speed={16}
              deletionSpeed={32}
              cursor={true}
              repeat={Number.POSITIVE_INFINITY}
            />
            <br />
            {props.suffix}
          </h1>
          <p className="mb-6 font-light text-gray-600 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">
            Navigating the Cloud Native landscape can be tough and just keeping
            your head above water is a challenge.
            <br />
            <br />
            We're here to help.
          </p>
          <a
            href={props.primaryButton.link}
            target={props.primaryButton.newWindow ? "_blank" : "_self"}
            className="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center rounded-lg text-black bg-gradient-to-br from-primary to-secondary hover:from-secondary hover:to-primary"
          >
            {props.primaryButton.text}
            <svg
              className="w-5 h-5 ml-2 -mr-1"
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fillRule="evenodd"
                d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                clipRule="evenodd"
              >
              </path>
            </svg>
          </a>

          <a
            href={props.secondaryButton.link}
            target={props.secondaryButton.newWindow ? "_blank" : "_self"}
            className="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800"
          >
            {props.secondaryButton.text}
          </a>
        </div>
        <div className="hidden lg:mt-0 lg:col-span-4 lg:flex">
          <img src={props.image.src} alt="Mix of Cloud Native Project Logos" />
        </div>
      </div>
    </section>
  );
};

export default Typewriter;
